server:
  port: 8081
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: Authorization
          uri: http://localhost:8084/
          predicates:
            - Path=/authenticate/**
        - id: order
          uri: http://localhost:8083/
          predicates:
            - Path=/order/api/**
        - id: restaurant
          uri: http://localhost:8082/
          predicates:
            - Path=/restaurant/api/**
        - id: customer
          uri: http://localhost:8086/
          predicates:
              - Path=/customer/api/**
        - id: driver
          uri: http://localhost:8085/
          predicates:
              - Path=/driver/api/**