server:
  port: 8081
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8083/
          predicates:
            - Path=/order/api/**
        - id: restaurant
          uri: http://localhost:8082/
          predicates:
            - Path=/restaurant/api/**